const eventsData2 = [
    {
        title: "Electronic Music Festival",
        subtitle: "A night of electrifying beats",
        image: "https://sarieva.org/data/i/ST2.jpeg",
        description:
            "An electrifying night of music with top DJs from around the world.",
        categories: ["Music"],
        location: "New York",
        venue: "S2xeuMjZBPFa9TMrZbXQ",
        eventEndDate: "2025-03-30T20:00:00Z",
        openingDateTime: "2025-03-01T18:00:00Z",
        openingDurationHours: 3,
        associatedLinks: ["https://eventwebsite.com"],
        staged: true,
        attending: ["user1"],
        interested: ["user1"],
        invited: ["user1"],
        ratingAvg: 5,
        totalRatings: 42,
        relatedEvents: ["event987"],
        createdBy: "user123",
    },
    {
        title: "Contemporary Art Exhibition",
        subtitle: "Explore modern artistic expressions",
        image: "https://sarieva.org/data/i/ST2.jpeg",
        description:
            "Explore the latest trends in modern art with international artists.",
        categories: ["Art", "Exhibition"],
        location: "San Francisco",
        venue: "venue456",
        eventEndDate: "2025-04-15T20:00:00Z",
        openingDateTime: "2025-04-10T18:00:00Z",
        openingDurationHours: 4,
        associatedLinks: ["https://artwebsite.com"],
        staged: true,
        attending: ["user2"],
        interested: ["user3"],
        invited: ["user4"],
        ratingAvg: 4.8,
        totalRatings: 35,
        relatedEvents: ["event654"],
        createdBy: "user123",
    },
    {
        title: "Startup Networking Event",
        subtitle: "Meet investors & founders",
        image: "https://sarieva.org/data/i/ST2.jpeg",
        description:
            "Meet entrepreneurs and investors in this exclusive startup networking event.",
        categories: ["Business", "Networking"],
        location: "San Francisco",
        venue: "venue789",
        eventEndDate: "2025-06-10T20:00:00Z",
        openingDateTime: "2025-06-05T18:00:00Z",
        openingDurationHours: 2,
        associatedLinks: ["https://startupnetwork.com"],
        staged: true,
        attending: ["user5"],
        interested: ["user6"],
        invited: ["user7"],
        ratingAvg: 4.5,
        totalRatings: 28,
        relatedEvents: ["event321"],
        createdBy: "user789",
    },
    {
        title: "Culinary Masterclass",
        subtitle: "Learn gourmet cooking",
        image: "https://sarieva.org/data/i/ST2.jpeg",
        description:
            "Learn gourmet cooking techniques from world-renowned chefs.",
        categories: ["Food", "Workshops"],
        location: "New York",
        venue: "venue101",
        eventEndDate: "2025-05-20T20:00:00Z",
        openingDateTime: "2025-05-15T18:00:00Z",
        openingDurationHours: 5,
        associatedLinks: ["https://culinarymaster.com"],
        staged: true,
        attending: ["user8"],
        interested: ["user9"],
        invited: ["user10"],
        ratingAvg: 4.7,
        totalRatings: 22,
        relatedEvents: ["event654"],
        createdBy: "user101",
    },
    {
        title: "Live Theatre Performance",
        subtitle: "A breathtaking live performance",
        image: "https://sarieva.org/data/i/ST2.jpeg",
        description: "A breathtaking live performance by award-winning actors.",
        categories: ["Theatre", "Performance"],
        location: "Los Angeles",
        venue: "venue202",
        eventEndDate: "2025-07-10T20:00:00Z",
        openingDateTime: "2025-07-05T18:00:00Z",
        openingDurationHours: 3,
        associatedLinks: ["https://theatreshow.com"],
        staged: true,
        attending: ["user11"],
        interested: ["user12"],
        invited: ["user13"],
        ratingAvg: 4.9,
        totalRatings: 50,
        relatedEvents: ["event999"],
        createdBy: "user202",
    },
    {
        title: "Photography Workshop",
        subtitle: "Enhance your photography skills",
        image: "https://sarieva.org/data/i/ST2.jpeg",
        description:
            "Enhance your photography skills with professional guidance.",
        categories: ["Workshops", "Photography"],
        location: "Los Angeles",
        venue: "venue303",
        eventEndDate: "2025-08-05T20:00:00Z",
        openingDateTime: "2025-08-01T18:00:00Z",
        openingDurationHours: 6,
        associatedLinks: ["https://photoworkshop.com"],
        staged: true,
        attending: ["user14"],
        interested: ["user15"],
        invited: ["user16"],
        ratingAvg: 4.6,
        totalRatings: 30,
        relatedEvents: ["event555"],
        createdBy: "user303",
    },
    {
        title: "Tech Conference 2025",
        subtitle: "Latest tech trends & innovations",
        image: "https://sarieva.org/data/i/ST2.jpeg",
        description:
            "Get insights into the latest tech trends from industry leaders.",
        categories: ["Technology", "Conference"],
        location: "San Francisco",
        venue: "venue404",
        eventEndDate: "2025-09-15T20:00:00Z",
        openingDateTime: "2025-09-10T18:00:00Z",
        openingDurationHours: 7,
        associatedLinks: ["https://techconference.com"],
        staged: true,
        attending: ["user17"],
        interested: ["user18"],
        invited: ["user19"],
        ratingAvg: 4.9,
        totalRatings: 65,
        relatedEvents: ["event777"],
        createdBy: "user404",
    },
];

export default eventsData2;
